services:
  sampleproject:
    image: sampleproject
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    expose:
      - "3001"
    ports:
      - "3000:3001"
    